/*
 * LVGL9 Icon Header: phone_app_icon
 * Generated by generate_icon.py
 */

#ifndef _PHONE_APP_ICON_H_
#define _PHONE_APP_ICON_H_

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_image_dsc_t phone_app_icon;

#ifdef __cplusplus
}
#endif

#endif /* _PHONE_APP_ICON_H_ */
