/*
 * LVGL9 Icon Header: camera_app_icon
 * Generated by generate_icon.py
 */

#ifndef _CAMERA_APP_ICON_H_
#define _CAMERA_APP_ICON_H_

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_image_dsc_t camera_app_icon;

#ifdef __cplusplus
}
#endif

#endif /* _CAMERA_APP_ICON_H_ */
